/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var obsidian = require("obsidian");

var HeadingColorsPlugin = class extends obsidian.Plugin {
  async onload() {
    console.log("Heading Colors plugin loaded");
  }

  onunload() {}
};

module.exports = HeadingColorsPlugin;
